# Generated by Django 5.0.3 on 2024-03-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
